"""add timestamp to shortlink table

Revision ID: 7897d8f83502
Revises: 70eb6251562f
Create Date: 2025-10-19 18:31:45.221733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7897d8f83502'
down_revision: Union[str, Sequence[str], None] = '70eb6251562f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortlinks', sa.Column('created_at', sa.Date(), nullable=False))
    op.add_column('shortlinks', sa.Column('updated_at', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortlinks', 'updated_at')
    op.drop_column('shortlinks', 'created_at')
    # ### end Alembic commands ###
