"""create foreign keys

Revision ID: dcd119989255
Revises: b2f39eba2ae1
Create Date: 2025-10-15 23:23:55.879122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'dcd119989255'
down_revision: Union[str, Sequence[str], None] = 'b2f39eba2ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_shortlink_clicks_shortlink_id_shortlinks'), 'shortlink_clicks', 'shortlinks', ['shortlink_id'], ['id'])
    op.drop_constraint(op.f('shortlinks_short_url_key'), 'shortlinks', type_='unique')
    op.create_unique_constraint(op.f('uq_shortlinks_short_url'), 'shortlinks', ['short_url'])
    op.create_foreign_key(op.f('fk_shortlinks_user_id_user'), 'shortlinks', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('fk_shortlinks_user_id_user'), 'shortlinks', type_='foreignkey')
    op.drop_constraint(op.f('uq_shortlinks_short_url'), 'shortlinks', type_='unique')
    op.create_unique_constraint(op.f('shortlinks_short_url_key'), 'shortlinks', ['short_url'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('fk_shortlink_clicks_shortlink_id_shortlinks'), 'shortlink_clicks', type_='foreignkey')
    # ### end Alembic commands ###
