"""update user_id to nullable

Revision ID: fe20d4d1e83f
Revises: dcd119989255
Create Date: 2025-10-18 22:15:38.123087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'fe20d4d1e83f'
down_revision: Union[str, Sequence[str], None] = 'dcd119989255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shortlinks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_shortlinks_user_id_user'), 'shortlinks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shortlinks_user_id_user'), 'shortlinks', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_shortlinks_user_id_user'), 'shortlinks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shortlinks_user_id_user'), 'shortlinks', 'user', ['user_id'], ['id'])
    op.alter_column('shortlinks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
